### ISSUE TITLE
Implementação do carrinho

### ISSUE THREAD

**Issue by MarcelReis** [Squad-1-React-Codenation/Fashionista#82]
As tarefas tem que ser feitas em sequencia pois alteram a estrutura do estado
 - [x] Implementar ações iniciais de adicionar, remover e limpar carrinho #71
 - [ ] Melhoria permitindo remover e adicionar itens especificos do carrinho #83 
 - [ ] Salvar valor do carrinho na store (calcular) #84
